### ISSUE TITLE
Example doesn't build anymore due to js_ffi breakage

### ISSUE THREAD

**Issue by tommythorn** [richardanaya/hyperpixel#3]
Hyperpixel looks so nice, but unfortunately the examples doesn't build with Rust 1.62:
```
$ cd examples/static
$ make
...
   Compiling anystring v0.0.2
   Compiling js_ffi v0.6.9
   Compiling js_ffi v0.5.4
error[E0535]: invalid argument
  --> /Users/tommy/.cargo.x86_64-darwin/registry/src/github.com-1ecc6299db9ec823/js_ffi-0.5.4/src/lib.rs:61:14
   |
61 |     #[inline(Always)]
   |              ^^^^^^
```
Clearly js_ffi v0.5.4 is an issue.  Unfortunately, naively bumping js_ffi to 0.6 doesn't work
```
   Compiling js_ffi v0.6.9
   Compiling js_ffi v0.8.0
   Compiling rand v0.7.3
   Compiling web_timer v0.1.5
   Compiling hyperpixel v0.1.2 (/Users/tommy/truenas/projects/Rust/hyperpixel)
   Compiling web_random v0.0.2
   Compiling example v0.1.0 (/Users/tommy/truenas/projects/Rust/hyperpixel/examples/static)
warning: Linking globals named 'jsfficallback': symbol multiply defined!

error: failed to load bitcode of module "js_ffi-8981a035de6f4750.js_ffi.bac442bd-cgu.0.rcgu.o": 
```
Bumping the `web_timer` and `web_random` also doesn't  work as their API has changed in an incompatible way.

Has anyone solve this or alternatively is there a different approach I should try?

**Comment by tommythorn** [comment]
I tried to bump js_ffi (multiple references) and finally discovered that it has been deprecated in favor of https://github.com/richardanaya/js-wasm.  It looks to me that the latter can completely replace this crate, but it would be nice if the static example was included directly in js-wasm.
